<?xml version="1.0" encoding="UTF-8"?>
<pd:ProcessDefinition xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns="http://www.tibco.com/pe/EngineTypes" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlPfx="http://www.tibco.com/CommonLE2/namespace/Administration/GUIServices/ExceptionConfiguration" xmlns:ns12="http://www.tibco.com/CommonLE/namespace/Common" xmlns:pfx="http://www.tibco.com/pe/DeployedVarsType" xmlns:pd="http://xmlns.tibco.com/bw/process/2003" xmlns:ns2="http://www.tibco.com/CommonLE2/namespace/Administration/GUIServices/Applications/1175798793750" xmlns:ns1="http://www.tibco.com/pe/GenerateErrorActivity/InputSchema" xmlns:ns4="http://www.tibco.com/CommonLE2/Private/Administration" xmlns:ns3="http://www.tibco.com/CommonLE2/Public/Common" xmlns:pfx4="http://www.tibco.com/CommonLE2/Public/Common/Dummy" xmlns:pfx3="http://www.tibco.com/CommonLE2/namespace/Public/Pluggable/GUI/Configuration/ExceptionConfig" xmlns:pfx2="http://www.tibco.com/CommonLE2/namespace/private/Common">
    <wsdl:import namespace="http://www.tibco.com/CommonLE2/namespace/Administration/GUIServices/ExceptionConfiguration" location="/SharedResources/WSDL/GUI/Administration/intfRetrieveSpecificExceptionConfigurationList.wsdl"/>
    <pd:name>Administration/GUIServices/ExceptionConfigurationServices/wsCreateExceptionConfiguration.process</pd:name>
    <pd:startName>Start</pd:startName>
    <pd:startType wsMsgRef="wsdlPfx:ExceptionConfigs"/>
    <pd:startX>150</pd:startX>
    <pd:startY>50</pd:startY>
    <pd:returnBindings>
        <wsdlPfx:Dummy/>
    </pd:returnBindings>
    <pd:endName>End</pd:endName>
    <pd:endType wsMsgRef="wsdlPfx:Dummy"/>
    <pd:endX>427</pd:endX>
    <pd:endY>45</pd:endY>
    <pd:errorSchemas>
        <Schema1 wsMsgRef="wsdlPfx:Error"/>
    </pd:errorSchemas>
    <pd:processVariables/>
    <pd:targetNamespace>http://xmlns.example.com/1285643939531</pd:targetNamespace>
    <pd:activity name="Create Exception Configuration">
        <pd:type>com.tibco.pe.core.CallProcessActivity</pd:type>
        <pd:resourceType>ae.process.subprocess</pd:resourceType>
        <pd:x>273</pd:x>
        <pd:y>53</pd:y>
        <config>
            <processName>/Administration/Logic/ExceptionConfiguration/CreateExceptionConfiguration.process</processName>
            <processNameXPath/>
        </config>
        <pd:inputBindings>
            <xsl:for-each select="$Start/wsdlPfx:ExceptionConfigs/parameters/pfx3:ExceptionConfigs/pfx3:ExceptionConfig[1]">
                <ns4:ExceptionConfigurationUpdate>
                    <ns4:ApplicationID>
                        <xsl:value-of select="pfx3:ApplicationID"/>
                    </ns4:ApplicationID>
                    <ns4:ExceptionCode>
                        <xsl:value-of select="pfx3:ExceptionCode"/>
                    </ns4:ExceptionCode>
                    <ns4:CategoryID>
                        <xsl:value-of select="pfx3:CategoryID"/>
                    </ns4:CategoryID>
                    <ns4:TypeID>
                        <xsl:value-of select="pfx3:TypeID"/>
                    </ns4:TypeID>
                    <ns4:SeverityID>
                        <xsl:value-of select="pfx3:SeverityID"/>
                    </ns4:SeverityID>
                    <xsl:if test="pfx3:ProcedureID">
                        <ns4:ProcedureID>
                            <xsl:value-of select="pfx3:ProcedureID"/>
                        </ns4:ProcedureID>
                    </xsl:if>
                    <ns4:Description>
                        <xsl:value-of select="pfx3:Description"/>
                    </ns4:Description>
                    <xsl:if test="pfx3:ReplyDestination">
                        <ns4:ReplyDestination>
                            <xsl:value-of select="pfx3:ReplyDestination"/>
                        </ns4:ReplyDestination>
                    </xsl:if>
                    <xsl:if test="pfx3:RoleName">
                        <ns4:RoleName>
                            <xsl:value-of select="pfx3:RoleName"/>
                        </ns4:RoleName>
                    </xsl:if>
                    <xsl:if test="pfx3:NotificationChnl">
                        <ns4:NotificationChnl>
                            <xsl:value-of select="pfx3:NotificationChnl"/>
                        </ns4:NotificationChnl>
                    </xsl:if>
                    <xsl:if test="pfx3:EmailTo">
                        <ns4:EmailTo>
                            <xsl:value-of select="pfx3:EmailTo"/>
                        </ns4:EmailTo>
                    </xsl:if>
                    <xsl:if test="pfx3:EmailCC">
                        <ns4:EmailCC>
                            <xsl:value-of select="pfx3:EmailCC"/>
                        </ns4:EmailCC>
                    </xsl:if>
                    <xsl:if test="pfx3:Exceptionttl">
                        <ns4:Exceptionttl>
                            <xsl:value-of select="pfx3:Exceptionttl"/>
                        </ns4:Exceptionttl>
                    </xsl:if>
                    <xsl:if test="pfx3:Instruction">
                        <ns4:Instruction>
                            <xsl:value-of select="pfx3:Instruction"/>
                        </ns4:Instruction>
                    </xsl:if>
                    <xsl:if test="pfx3:EventType">
                        <ns4:EventType>
                            <xsl:value-of select="pfx3:EventType"/>
                        </ns4:EventType>
                    </xsl:if>
                    <xsl:if test="pfx3:ResolveDelayInterval">
                        <ns4:ResolveDelayInterval>
                            <xsl:value-of select="pfx3:ResolveDelayInterval"/>
                        </ns4:ResolveDelayInterval>
                    </xsl:if>
                </ns4:ExceptionConfigurationUpdate>
            </xsl:for-each>
        </pd:inputBindings>
    </pd:activity>
    <pd:activity name="Catch Exception Code Exists">
        <pd:type>com.tibco.pe.core.CatchActivity</pd:type>
        <pd:resourceType>ae.activities.catch</pd:resourceType>
        <pd:x>128</pd:x>
        <pd:y>174</pd:y>
        <pd:handler>true</pd:handler>
        <config>
            <fault>localname=IDNotUnique namespace=http://www.tibco.com/CommonLE2/namespace/private/Common</fault>
        </config>
        <pd:inputBindings/>
    </pd:activity>
    <pd:activity name="Generate Error">
        <pd:type>com.tibco.pe.core.GenerateErrorActivity</pd:type>
        <pd:resourceType>ae.activities.throw</pd:resourceType>
        <pd:x>385</pd:x>
        <pd:y>165</pd:y>
        <config>
            <faultName>Schema1</faultName>
        </config>
        <pd:inputBindings>
            <ns1:ActivityInput>
                <xsl:if test="$Catch-Exception-Code-Exists/pfx2:IDNotUnique/pfx2:Message">
                    <message>
                        <xsl:value-of select="$Catch-Exception-Code-Exists/pfx2:IDNotUnique/pfx2:Message"/>
                    </message>
                </xsl:if>
                <xsl:if test="$Catch-Exception-Code-Exists/pfx2:IDNotUnique/pfx2:Code">
                    <messageCode>
                        <xsl:value-of select="$Catch-Exception-Code-Exists/pfx2:IDNotUnique/pfx2:Code"/>
                    </messageCode>
                </xsl:if>
                <data>
                    <wsdlPfx:Error>
                        <parameters>
                            <ns3:Error>
                                <xsl:if test="$Catch-Exception-Code-Exists/pfx2:IDNotUnique/pfx2:Message">
                                    <ns3:Message>
                                        <xsl:value-of select="$Catch-Exception-Code-Exists/pfx2:IDNotUnique/pfx2:Message"/>
                                    </ns3:Message>
                                </xsl:if>
                                <xsl:if test="$Catch-Exception-Code-Exists/pfx2:IDNotUnique/pfx2:Code">
                                    <ns3:Code>
                                        <xsl:value-of select="$Catch-Exception-Code-Exists/pfx2:IDNotUnique/pfx2:Code"/>
                                    </ns3:Code>
                                </xsl:if>
                            </ns3:Error>
                        </parameters>
                    </wsdlPfx:Error>
                </data>
            </ns1:ActivityInput>
        </pd:inputBindings>
    </pd:activity>
    <pd:activity name="Catch All Errors">
        <pd:type>com.tibco.pe.core.CatchActivity</pd:type>
        <pd:resourceType>ae.activities.catch</pd:resourceType>
        <pd:x>110</pd:x>
        <pd:y>271</pd:y>
        <pd:handler>true</pd:handler>
        <config>
            <catchAll>true</catchAll>
        </config>
        <pd:inputBindings/>
    </pd:activity>
    <pd:activity name="Local Exception Handler">
        <pd:type>com.tibco.pe.core.CallProcessActivity</pd:type>
        <pd:resourceType>ae.process.subprocess</pd:resourceType>
        <pd:x>272</pd:x>
        <pd:y>278</pd:y>
        <config>
            <processName>/Common/Local Exception Handler.process</processName>
        </config>
        <pd:inputBindings>
            <ns12:Exception>
                <ErrorMessage>
                    <xsl:value-of select="$_error/ns:ErrorReport/Msg"/>
                </ErrorMessage>
                <ErrorCode>
                    <xsl:value-of select="$_error/ns:ErrorReport/MsgCode"/>
                </ErrorCode>
                <ns12:Error>
                    <xsl:for-each xmlns:xsl="http://www.w3.org/1999/XSL/Transform" select="$_error/ns:ErrorReport">
                        <ns12:ErrorReport>
                            <StackTrace>
                                <xsl:value-of select="StackTrace"/>
                            </StackTrace>
                            <Msg>
                                <xsl:value-of select="Msg"/>
                            </Msg>
                            <FullClass>
                                <xsl:value-of select="FullClass"/>
                            </FullClass>
                            <Class>
                                <xsl:value-of select="Class"/>
                            </Class>
                            <ProcessStack>
                                <xsl:value-of select="ProcessStack"/>
                            </ProcessStack>
                            <MsgCode>
                                <xsl:value-of select="MsgCode"/>
                            </MsgCode>
                        </ns12:ErrorReport>
                    </xsl:for-each>
                </ns12:Error>
            </ns12:Exception>
        </pd:inputBindings>
    </pd:activity>
    <pd:activity name="Generate Internal Error">
        <pd:type>com.tibco.pe.core.GenerateErrorActivity</pd:type>
        <pd:resourceType>ae.activities.throw</pd:resourceType>
        <pd:x>418</pd:x>
        <pd:y>276</pd:y>
        <config>
            <faultName>Schema1</faultName>
        </config>
        <pd:inputBindings>
            <ns1:ActivityInput>
                <message>
                    <xsl:value-of select="$_error/ns:ErrorReport/Msg"/>
                </message>
                <messageCode>
                    <xsl:value-of select="$_error/ns:ErrorReport/MsgCode"/>
                </messageCode>
                <data>
                    <wsdlPfx:Error>
                        <parameters>
                            <ns3:Error>
                                <ns3:Message>
                                    <xsl:value-of select="$_error/ns:ErrorReport/Msg"/>
                                </ns3:Message>
                                <ns3:Code>
                                    <xsl:value-of select="$_error/ns:ErrorReport/MsgCode"/>
                                </ns3:Code>
                            </ns3:Error>
                        </parameters>
                    </wsdlPfx:Error>
                </data>
            </ns1:ActivityInput>
        </pd:inputBindings>
    </pd:activity>
    <pd:activity name="Catch AppID Does Not Exist">
        <pd:type>com.tibco.pe.core.CatchActivity</pd:type>
        <pd:resourceType>ae.activities.catch</pd:resourceType>
        <pd:x>127</pd:x>
        <pd:y>370</pd:y>
        <pd:handler>true</pd:handler>
        <config>
            <fault>localname=ReferencialIntegrityViolation namespace=http://www.tibco.com/CommonLE2/namespace/private/Common</fault>
        </config>
        <pd:inputBindings/>
    </pd:activity>
    <pd:activity name="Generate Referencial Error">
        <pd:type>com.tibco.pe.core.GenerateErrorActivity</pd:type>
        <pd:resourceType>ae.activities.throw</pd:resourceType>
        <pd:x>320</pd:x>
        <pd:y>372</pd:y>
        <config>
            <faultName>Schema1</faultName>
        </config>
        <pd:inputBindings>
            <ns1:ActivityInput>
                <message>
                    <xsl:value-of select="$Catch-AppID-Does-Not-Exist/pfx2:ReferencialIntegrityViolation/pfx2:Message"/>
                </message>
                <messageCode>
                    <xsl:value-of select="$Catch-AppID-Does-Not-Exist/pfx2:ReferencialIntegrityViolation/pfx2:Code"/>
                </messageCode>
                <data>
                    <wsdlPfx:Error>
                        <parameters>
                            <ns3:Error>
                                <ns3:Message>
                                    <xsl:value-of select="$Catch-AppID-Does-Not-Exist/pfx2:ReferencialIntegrityViolation/pfx2:Message"/>
                                </ns3:Message>
                                <ns3:Code>
                                    <xsl:value-of select="$Catch-AppID-Does-Not-Exist/pfx2:ReferencialIntegrityViolation/pfx2:Code"/>
                                </ns3:Code>
                            </ns3:Error>
                        </parameters>
                    </wsdlPfx:Error>
                </data>
            </ns1:ActivityInput>
        </pd:inputBindings>
    </pd:activity>
    <pd:transition>
        <pd:from>Start</pd:from>
        <pd:to>Create Exception Configuration</pd:to>
        <pd:lineType>Default</pd:lineType>
        <pd:lineColor>-16777216</pd:lineColor>
        <pd:conditionType>always</pd:conditionType>
    </pd:transition>
    <pd:transition>
        <pd:from>Create Exception Configuration</pd:from>
        <pd:to>End</pd:to>
        <pd:lineType>Default</pd:lineType>
        <pd:lineColor>-16777216</pd:lineColor>
        <pd:conditionType>always</pd:conditionType>
    </pd:transition>
    <pd:transition>
        <pd:from>Catch Exception Code Exists</pd:from>
        <pd:to>Generate Error</pd:to>
        <pd:lineType>Default</pd:lineType>
        <pd:lineColor>-16777216</pd:lineColor>
        <pd:conditionType>always</pd:conditionType>
    </pd:transition>
    <pd:transition>
        <pd:from>Catch All Errors</pd:from>
        <pd:to>Local Exception Handler</pd:to>
        <pd:lineType>Default</pd:lineType>
        <pd:lineColor>-16777216</pd:lineColor>
        <pd:conditionType>always</pd:conditionType>
    </pd:transition>
    <pd:transition>
        <pd:from>Local Exception Handler</pd:from>
        <pd:to>Generate Internal Error</pd:to>
        <pd:lineType>Default</pd:lineType>
        <pd:lineColor>-16777216</pd:lineColor>
        <pd:conditionType>always</pd:conditionType>
    </pd:transition>
    <pd:transition>
        <pd:from>Catch AppID Does Not Exist</pd:from>
        <pd:to>Generate Referencial Error</pd:to>
        <pd:lineType>Default</pd:lineType>
        <pd:lineColor>-16777216</pd:lineColor>
        <pd:conditionType>always</pd:conditionType>
    </pd:transition>
</pd:ProcessDefinition>